export const CLIENT_ID = "7b414530c229452986b6318b1a178be0"
export const REDIRECT_URI = "http://localhost:3000/main"
export const AUTH_ENDPOINT = "https://accounts.spotify.com/authorize"
export const RESPONSE_TYPE = "token"
export const SCOPES = "ugc-image-upload user-read-recently-played user-top-read user-read-playback-position user-read-playback-state user-modify-playback-state user-read-currently-playing app-remote-control playlist-modify-public playlist-modify-private playlist-read-private playlist-read-collaborative user-follow-modify user-follow-read user-library-modify user-library-read user-read-email user-read-private"
